//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63131717.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CT_PM
    {
        public int ID { get; set; }
        [DisplayName("ID phiếu mượn")]
        public Nullable<int> IDPM { get; set; }
        [DisplayName("ID độc giả")]
        public Nullable<int> IDDG { get; set; }
        [DisplayName("ID sách")]
        public Nullable<int> IDSach { get; set; }
        [DisplayName("Tên sách")]
        public string TenSach { get; set; }
        [DisplayName("Số lượng")]
        public Nullable<int> SoLuong { get; set; }
        [DisplayName("Trạng thái")]
        public string TrangThai { get; set; }
        [DisplayName("Ngày trả thực tế")]
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> NgayTraThucTe { get; set; }
        public virtual DocGia DocGia { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual Sach Sach { get; set; }
        public virtual TrangThai TrangThai1 { get; set; }
    }
}
