//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63131717.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PhieuMuon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuMuon()
        {
            this.CT_PM = new HashSet<CT_PM>();
        }
        [DisplayName("ID phiếu mượn")]
        public int IDPM { get; set; }
        [DisplayName("ID độc giả")]
        public Nullable<int> IDDG { get; set; }
        [DisplayName("Ngày mượn")]
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> NgayMuon { get; set; }
        [DisplayName("Ngày trả")]
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> NgayTra { get; set; }
        [DisplayName("Tiền phạt")]
        public Nullable<int> TienPhat { get; set; }
        [DisplayName("Ghi chú")]
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PM> CT_PM { get; set; }
        public virtual DocGia DocGia { get; set; }
    }
}
